### ISSUE TITLE
How to style the Android picker

### ISSUE THREAD

**Issue by delanick** [davecoffin/nativescript-modal-datetimepicker#11]
Hi, how do I style the Android modal picker(s)? I'd like to change the colours. Please advise.

**Comment by shiv19** [comment]
You will have to add the styles to `App_Resources/android/values-21/styles.xml`
you can read the android docs for the list of available customizations,
or you can read this SO article
https://stackoverflow.com/questions/32549992/how-to-customize-timepicker-in-material-design-android
