### ISSUE TITLE
Custom colors

### ISSUE THREAD

**Issue by whins** [davecoffin/nativescript-modal-datetimepicker#12]
Hi!
How to chantge basic colors?
Thanks

**Comment by eddami** [comment]
Hello, This is a bit late but this may help someone else.
This is my solution for android.

Go to `App_Resources/Android/values-21/styles.xml`
From there you can edit your DateTimePicker colors.
For example let's edit the header background color of DatePicker:
```
<style name="SpinnerDatePicker" parent="android:Widget.Material.Light.DatePicker">
    <item name="android:datePickerMode">calendar</item>
    <item name="android:headerBackground">@color/ns_accent</item>
</style>
```

This is list of items you can override:
```
headerBackground
dayOfWeekBackground
dayOfWeekTextAppearance
headerMonthTextAppearance
headerDayOfMonthTextAppearance
headerYearTextAppearance
headerSelectedTextColor
yearListItemTextAppearance
yearListSelectorColor
calendarTextColor
calendarSelectedTextColor
```

**Comment by MCurran16** [comment]
@moeddami Where did you find those values? 3 out of the 5 I just added did not work. Any advice?

**Comment by eddami** [comment]
@MCurran16 Check this: [Android DatePicker XML attributes](https://developer.android.com/reference/android/widget/DatePicker#xml-attributes_1).
