### ISSUE TITLE
Cannot set startingMinute to 0

### ISSUE THREAD

**Issue by cerireyhan** [davecoffin/nativescript-modal-datetimepicker#19]
### Which platform(s) does your issue occur on?
- iOS and Android
- android emulator and device (iPhone X) 
- latest release

**Steps to Reproduce**
Step 1: Inside options parameter of pickTime() method, set the startingMinute to 0 and startingHour to 11 in order to display 11:00
Expected Behavior: Spinner shows minute 00.
Result: Spinner shows the current minute instead of 00. Displayed hour is correct. (eg. 11:06)
Workaround: Set startingMinute to 60 in order to display it as 00.

**Comment by sedrak1987** [comment]
In 1.1.5 version is it solved?

**Comment by shiv19** [comment]
Should be

**Comment by sedrak1987** [comment]
I set startingHour:0,startingMinute:0 in new version, but still see same result(current hour, minute)

**Comment by shiv19** [comment]
Thanks, will release a fix tonight. Has been pending from a long time

**Comment by sedrak1987** [comment]
maybe set 60 ?

**Comment by shiv19** [comment]
No, after next update, you'll be able to set it to 0 :)

**Comment by sedrak1987** [comment]
Dear friend, my purpose is set 00:00. Hope tomorrow can get it worked

**Comment by sedrak1987** [comment]
So nativescript-modal-datetimepicker package is your work?

**Comment by shiv19** [comment]
Yes, me and Dave. Let me finish this long waiting bug fix now

**Comment by shiv19** [comment]
Fixed in 1.1.6 @sedrak1987  @cerireyhan

**Comment by sedrak1987** [comment]
Thanks a lot. Works! *****

**Comment by sedrak1987** [comment]
Dear friend can you also fix is24HourView: true problem in IOS? It doesn't work in IOS

**Comment by shiv19** [comment]
That feature is simply not implemented in iOS, if you know how to do it, a PR would be welcome

**Comment by sedrak1987** [comment]
I'm newer in NS. If you will have solution, please let me know. Thanks.

**Comment by sedrak1987** [comment]
Also in IOS 00:00 show as 12:00 AM. Is it normal?

**Comment by shiv19** [comment]
Yes that seems normal to me

**Comment by sedrak1987** [comment]
ok. Thanks @ # @shiv19 

>
