### ISSUE TITLE
Can't change to spinner mode in android

### ISSUE THREAD

**Issue by yclau** [davecoffin/nativescript-modal-datetimepicker#23]
Hi @davecoffin , I follow configuration below and change to spinner. but still show in calendar mode. Isn't i set wrong configuration
```
App_Resources/Android/values-21/styles.xml

<!-- Default style for DatePicker - in spinner mode -->
<style name="SpinnerDatePicker" parent="android:Widget.Material.Light.DatePicker">
    <item name="android:datePickerMode">calendar</item>
</style>
 
<!-- Default style for TimePicker - in spinner mode -->
<style name="SpinnerTimePicker" parent="android:Widget.Material.Light.TimePicker">
    <item name="android:timePickerMode">clock</item>
</style>
```

```
{
	"description": "NativeScript Application",
	"license": "SEE LICENSE IN <your-license-filename>",
	"readme": "NativeScript Application",
	"repository": "<fill-your-repository-here>",
	"nativescript": { 
		"tns-android": {
			"version": "4.0.1"
		},
		"tns-ios": {
			"version": "4.0.1"
		}
	},
	"dependencies": {
		"nativescript-drop-down": "^3.2.4",
		"nativescript-iqkeyboardmanager": "^1.3.0",
		"nativescript-loading-indicator": "^2.4.0",
		"nativescript-localize": "^3.0.2",
		"nativescript-masked-text-field": "^2.0.2",
		"nativescript-modal-datetimepicker": "^1.1.3",
		"nativescript-pdf-view": "^2.0.1",
		"nativescript-theme-core": "^1.0.4",
		"nativescript-ui-listview": "^3.5.5",
		"tns-core-modules": "^4.0.0"
	},
	"devDependencies": {
		"babel-traverse": "6.26.0",
		"babel-types": "6.26.0",
		"babylon": "6.18.0",
		"lazy": "1.0.11"
	}
}
```

**Comment by ashrafaa** [comment]
Yes @davecoffin I have the same issue as well on Android. Set everything as in the guide, yet it's still showing as calendar. Kinda pain now for the user (especially the older ones!) to reach their year.

Is there anything changed now in newer Android version?

**Comment by BearOutThere** [comment]
Same problem here.  Would strongly prefer the spinner control.   
tns-android - 4.2.0 / tns-core-modules - 4.2.1

Please let us know what can be done to fix this.  Thanks.

**Comment by shiv19** [comment]
With nativescript-modal-datetimepicker@1.1.8
you can now set datePickerMode to "spinner"

**Comment by JakubPawlak** [comment]
Unfortunately, DatePicker styles still not working in version 1.1.10. TimePicker is working though.

**Comment by BearOutThere** [comment]
Latest fixes worked for me.  Spinner appears on android.

**Comment by princy05** [comment]
@bearoutthere : Could you please share me how did you set it to spinner mode in your project? Because i tried do change my settings in styles.xml but still android is showing me calendar and not the spinner

**Comment by BearOutThere** [comment]
I'm using a generated theme for my app so i had to add the picker configuration to the theme block like so in Android/values-v21/styles.xml:

```
<style name="AppTheme" parent="AppThemeBase">
        <item name="android:windowTranslucentStatus">true</item>
        <item name="android:datePickerStyle">@style/SpinnerDatePicker</item>
        <item name="android:timePickerStyle">@style/SpinnerTimePicker</item>
        <item name="android:actionMenuTextColor">#ffffff</item>
        <item name="android:textColorSecondary">#ffffff</item>
    </style>
```

this works for me and overrides the separate setting as described in the documentation.  Also make sure that you got v 1.1.8 installed of the plugin.  Good luck.
