### ISSUE TITLE
starting hour and starting minute default to current hour/minute when set to zero.

### ISSUE THREAD

**Issue by simplec-dev** [davecoffin/nativescript-modal-datetimepicker#25]
starting hour and starting minute default to current hour/minute when set to zero.

For example, when I pass in the equivalent of 2:00, I get hour=2 and minute=current minute.

On the android side, that can be fixed by changing these statements:

            var hour = options.startingHour
                ? +options.startingHour
                : now.get(Calendar.HOUR_OF_DAY);
            var minute = options.startingMinute
                ? +options.startingMinute
                : now.get(Calendar.MINUTE);

to:

            var hour = (options.startingHour!=null && options.startingHour>=0)
                ? +options.startingHour
                : now.get(Calendar.HOUR_OF_DAY);
            var minute = (options.startingMinute!=null && options.startingMinute>=0)
                ? +options.startingMinute
                : now.get(Calendar.MINUTE);

iOS is very similar

**Comment by shiv19** [comment]
@simplec-dev Thanks for pointing out this bug.
Will be fixed soon!

**Comment by cerireyhan** [comment]
@shiv19 is there any progress on this?

**Comment by shiv19** [comment]
Fixed in 1.1.6 @cerireyhan 

sorry, it took too long. would have appreciated a PR instead.
Thanks @simplec-dev
