### ISSUE TITLE
Change style in App_Resources\Android\values-21\style.xml not working 

### ISSUE THREAD

**Issue by AshleyCao** [davecoffin/nativescript-modal-datetimepicker#29]
### Which platform(s) does your issue occur on?
-Android

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.1.0
- Cross-platform modules: 4.1.0
- Runtime(s): 4.1.2
- Plugin(s): "nativescript-modal-datetimepicker": "1.1.3",
### Please, tell us how to recreate the issue in as much detail as possible. 
This plugin is handy but setting style doesn't work for me. I am using android 5.1.0. I need to change text size for calendar. I tried with this https://android.googlesource.com/platform/frameworks/base/+/lollipop-release/core/res/res/values/styles_material.xml. No luck. And change datePickerMode  to spinner doesn't work for me either. 
### Is there any code involved? 
My app\App_Resources\Android\values-v21\style.xml file.
```
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:android="http://schemas.android.com/apk/res/android">

    <!-- Application theme -->
    <style name="AppTheme" parent="AppThemeBase">
        <item name="android:windowTranslucentStatus">true</item>
        <item name="android:datePickerStyle">@style/SpinnerDatePicker</item>
        <item name="android:timePickerStyle">@style/SpinnerTimePicker</item>
    </style>

    <!-- Default style for DatePicker - in spinner mode -->
    <style name="SpinnerDatePicker" parent="android:Widget.Material.Light.DatePicker">
        <item name="android:datePickerMode">calendar</item>
	    <item name="android:dayOfWeekTextAppearance">@style/TextAppearance.Material.DatePicker.DayOfWeekLabel</item>
       
    </style>
	
	<style name="TextAppearance.Material.DatePicker.DayOfWeekLabel" parent="android:TextAppearance.Material">
        <item name="android:textSize">24px</item>
    </style>
</resources>
```
Cheers

**Comment by JackThomson2** [comment]
Hi I also had the same issue I was able to solve it by removing this line 

https://github.com/davecoffin/nativescript-modal-datetimepicker/blob/5e31c2379f39c8b11062933c052affce698840ef/src/modal-datetimepicker.android.ts#L63

**Comment by AshleyCao** [comment]
@JackThomson2 Thanks for your reply. I remove the themeID from modal-datetimepicker.android.js and change style.xml as above. Still no difference

**Comment by JackThomson2** [comment]
@AshleyCao Hi, looking at the android docs, the style "android:dayOfWeekTextAppearance" only allow changing the colour of the text. However changing the picker to spinner does work on my local environment. It is worth noting live sync won't work if you edit the node modules directly you'll have to re-run tns run android.

**Comment by shiv19** [comment]
@JackThomson2 or you can do `tns run android --syncAllFiles` to sync changes in node_modules

**Comment by shiv19** [comment]
With nativescript-modal-datetimepicker@1.1.8
you can now set datePickerMode to "spinner"
