### ISSUE TITLE
Gray Patch Over Cancel and Done Button?

### ISSUE THREAD

**Issue by dlucidone** [davecoffin/nativescript-modal-datetimepicker#3]
![simulator screen shot - iphone 7 - 2017-11-22 at 17 06 10](https://user-images.githubusercontent.com/9256365/33125698-8d4f0ca2-cfa7-11e7-964e-9e2992294450.png)

I'm using this plugin on other pages as well but on one particular page this is appearing like this?
Any Help! Thanks!

**Comment by davecoffin** [comment]
Can you provide some more context? Nothing jumps to mind immediately, share some code.

**Comment by davecoffin** [comment]
Totally randomly I think I just stumbled upon the answer here. That looks like it might be the top of a keyboard if your simulator is using the hardware keyboard. Are you launching the picker as a result of tapping in a textfield? If so, your keyboard is opening, and you have a hardware keyboard connected in your simulator, and that top part is part of IQKeyboard. Thats my guess.

**Comment by dlucidone** [comment]
@davecoffin  Yeah true! you got it correct I tested it, but one more issue I resolved is by making text field editable. Don't know the reason but It resolved the blank gray patch opening issue.

**Comment by davecoffin** [comment]
Great!
