### ISSUE TITLE
Error is: Failed to build plugin nativescript-modal-datetimepicker

### ISSUE THREAD

**Issue by luisalcarasr** [davecoffin/nativescript-modal-datetimepicker#34]
### Which platform(s) does your issue occur on?
- Android
- Android 6.0 
- Moto E2

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.1.2
- Cross-platform modules: 4.1.1
- Runtime(s): 4.1.3
- Plugin(s): 
`
        "dependencies": {
                "@angular/animations": "~6.0.0",
                "@angular/common": "~6.0.0",
                "@angular/compiler": "~6.0.0",
                "@angular/core": "~6.0.0",
                "@angular/forms": "~6.0.0",
                "@angular/http": "~6.0.0",
                "@angular/platform-browser": "~6.0.0",
                "@angular/platform-browser-dynamic": "~6.0.0",
                "@angular/router": "~6.0.0",
                "nativescript-angular": "~6.0.0",
                "nativescript-modal-datetimepicker": "^1.1.3",
                "nativescript-theme-core": "~1.0.4",
                "reflect-metadata": "~0.1.8",
                "rxjs": "~6.1.0",
                "tns-core-modules": "~4.1.0",
                "zone.js": "^0.8.26"
        },
        "devDependencies": {
                "babel-traverse": "6.26.0",
                "babel-types": "6.26.0",
                "babylon": "6.18.0",
                "lazy": "1.0.11",
                "nativescript-dev-typescript": "~0.7.0",
                "typescript": "~2.7.2"
        }
`

### Please, tell us how to recreate the issue in as much detail as possible. 
Create a new project and install this plugin.
Execute: `tns run android`

### Is there any code involved? 
[Test.zip](https://github.com/davecoffin/nativescript-modal-datetimepicker/files/2261593/Test.zip)

**Comment by shiv19** [comment]
Did you try
`tns platform remove android`
`tns run android`?

**Comment by luisalcarasr** [comment]
Yes, I try it!

**Comment by luisalcarasr** [comment]
I have created a new project, copied the `package.json` file of the new project to my project and I have added again each of the plugins.
