### ISSUE TITLE
CANCEL button

### ISSUE THREAD

**Issue by jolee11** [davecoffin/nativescript-modal-datetimepicker#4]
I would like to know how to detect the dialog is closed caused by CANCEL button or Android back button! 

It is because I have allocated some resources before open the dialog. But, cannot release them if user tap CANCEL. 

Thank you very much!

**Comment by davecoffin** [comment]
There is currently no hook into that action. We can look into adding it, but in the meantime feel free to fork and submit a PR!

**Comment by jolee11** [comment]
Oh, I See! Thank you very much!

**Comment by Ahnert1** [comment]
@jolee11 @davecoffin This may help you, maybe not.  Simply check if the promise object contains any data:
```
this.picker.pickDate({
      title: "Select Your Birthday",
      theme: "dark",
      minDate: new Date(1900, 0, 1),
      maxDate: new Date(2018, 0, 1),
      startingDate: new Date(1900, 0, 1)
    }).then(result => {
      if (result) {
        //user tapped done
      } else{
        //user tapped cancel/back
      }
    });
```

**Comment by 84GigaX** [comment]
@Ahnert1 The code you've provided is not working on Android. Is it working for I-phone. I am getting the code to do a PR for Android as I know how to make it work on Android.

**Comment by Ahnert1** [comment]
@motardev My apologies.  My project is currently iOS only, so I did not test it on android.
My team is now refactoring our project so that we can release an android version of our app.  So if you do successfully complete a PR for this, it will be much appreciated!

**Comment by 84GigaX** [comment]
Pull request completed

**Comment by shiv19** [comment]
This will be a breaking change. As the people who use this plugin will have to update their handlers.

Why not reject instead of resolve? That won't be a breaking change.

**Comment by 84GigaX** [comment]
According to @Ahnert1 , it's already the way it is working on iOs. I wanted to make it work the same way on Android and iOs.
