### ISSUE TITLE
Programmatically close an open dialog

### ISSUE THREAD

**Issue by nikoTM** [davecoffin/nativescript-modal-datetimepicker#42]
I have a use case where I need to programmatically close the dialog after it has been opened if a certain event happens before choosing time. Currently, I can see that a `close` method is exposed for iOS, but not Android. I think this might be a useful thing to have. 

Also, any ideas how I can work around it in the meantime?

**Comment by shiv19** [comment]
Hey, thanks for letting us know about it.
Adding it now :)

**Comment by shiv19** [comment]
@nikoTM 
Functionality added for android, and published as v1.1.11,
readme updated

Cheers!

**Comment by nikoTM** [comment]
Impressive speed. Thanks!
