### ISSUE TITLE
Removing cancel button

### ISSUE THREAD

**Issue by meysam-mahmoodi** [davecoffin/nativescript-modal-datetimepicker#45]
Hello there
I'd like to remove cancel button. is there a way to that? 
I have two datepicker on inside of together, when user close both modals by cancel button, my app will be freezed for some seconds so I want to remove the cancel button.
thanks

**Comment by shiv19** [comment]
I would suggest using NativeScript's DatePicker widget inside a modal for your usecase.

https://docs.nativescript.org/angular/ui/ng-ui-widgets/date-picker

**Comment by meysam-mahmoodi** [comment]
I could solved the problem with other way, anyway thank you
