### ISSUE TITLE
Modal is blank on iOS 13.1

### ISSUE THREAD

**Issue by Willhay108-imprint** [davecoffin/nativescript-modal-datetimepicker#61]
### Which platform(s) does your issue occur on?

iOS

### Please, provide the following version numbers that your issue occurs with:

1.2.1 of Datepicker, 13.1 for iOS.

### Please, tell us how to recreate the issue in as much detail as possible. 
Open up a date picker, the picker is there as I can scroll the dates and feel the haptic feedback, however nothing is rendered inside the modal it is completely blank

![Image from iOS (3)](https://user-images.githubusercontent.com/53561489/66397412-b117a980-e9d3-11e9-9ee7-723e71f42994.png)

**Comment by dan-sel-tx** [comment]
I believe this is happening due to Dark Mode being set on the iPhone, a new Apple feature?
This is the behavior we are seeing when set to dark mode, though we do see the text we set for Choose a Date. We have theme: 'dark' set for the module, and have tried all the others with no fix yet.

**Comment by davecoffin** [comment]
Yea, so this is definitely dark mode turning the picker white. I can look into fixing this but if you need an urgent fix you can add this to Info.plist and it will use the light UI style for your app, which is probably what youll want to do anyway unless you are making the effort of your whole UI respecting the new feature
```
<key>UIUserInterfaceStyle</key>
<string>Light</string>
```

**Comment by dan-sel-tx** [comment]
Can confirm this solves this issue, and many others due to the mode change. Thanks Dave! This is one my favorite plugins, very well done.
Would love to have this same module with the ability to pass in a list of string items into a scroll picker.
One can dream... :)

**Comment by Willhay108-imprint** [comment]
Yep, the plist change indeed fixes it. Thank you very much!
