### ISSUE TITLE
How to set default date/time

### ISSUE THREAD

**Issue by ppyoosuf** [davecoffin/nativescript-modal-datetimepicker#62]
Hi,
Is is possible to set default date / time while show the picker ?

**Comment by blurp1478963** [comment]
Hi @ppyoosuf why did you close this? I don't find how to set the default value too...!
Someone has an idea?

**Comment by ppyoosuf** [comment]
You can set the staartingDate field of the picker

eg .pickDate({
				title: "Select Date",
				theme: "light",
				startingDate: defaultDate, //new Date()
				maxDate: new Date()
			})
