### ISSUE TITLE
Issues with iOS 14

### ISSUE THREAD

**Issue by mreall** [davecoffin/nativescript-modal-datetimepicker#68]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
The plugin worked fine on NS6. But after updating to NS7 the plugin's UI doesn't fully load and the app crashes when the "Cancel" or "Done" buttons are tapped.

### Which platform(s) does your issue occur on?
- iOS 14
- emulator: iPhone 8

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.0.8
- Cross-platform modules: 7.0.3
- Runtime(s): @nativescript/ios is 7.0.0
- Plugin(s): 
```
  "dependencies": {
    "@nativescript/core": "~7.0.0",
    "@nativescript/theme": "~2.3.0",
    "nativescript-modal-datetimepicker": "^1.2.2",
    "nativescript-vue": "~2.8.0"
  },
  "devDependencies": {
    "@babel/core": "~7.1.0",
    "@babel/preset-env": "~7.1.0",
    "@nativescript/ios": "7.0.0",
    "@nativescript/webpack": "~3.0.0",
    "babel-loader": "~8.0.0",
    "nativescript-vue-template-compiler": "~2.8.0",
    "node-sass": "^4.7.1",
    "vue-loader": "~15.9.3"
  },
```

### Please, tell us how to recreate the issue in as much detail as possible. 
Add the component to a page per the instructions and run the app. When attempting to load the plugin the screen looks like the following.  Clicking either button crashes the app.
![modal-datetimepicker-bug](https://user-images.githubusercontent.com/15823671/93831161-be0ac880-fc37-11ea-8116-ec9c274a78c6.png)

### Is there any code involved? 
[Download a sample project](https://github.com/davecoffin/nativescript-modal-datetimepicker/files/5258611/modal-datetimepicker.zip)

**Comment by shiv19** [comment]
Hi @mreall 
We haven't upgraded this plugin to support {N} 7 yet.
We'll be updating it very soon before the end of this week :)

**Comment by OPADA-Eng** [comment]
Same here. with NS 6 and ios 14.

**Comment by adrianpdaluz** [comment]
> Same here. with NS 6 and ios 14.

We're also getting the same issue on NS 6 and iOS 14

**Comment by deivdev** [comment]
same error, NS7 and iOS 14.

**Comment by OPADA-Eng** [comment]
Any updates?

**Comment by mreall** [comment]
Hi @shiv19, thanks for working on this fix. It looks like a PR has also been submitted. Do you have an update on when you'll have a working version published?

**Comment by shiv19** [comment]
@mreall thanks for letting me know about the PR, will release this soon and leave a message here :)

**Comment by shiv19** [comment]
@mreall 
Please upgrade to [nativescript-modal-datetimepicker@1.2.3](https://www.npmjs.com/package/nativescript-modal-datetimepicker)
I've upgraded the plugin demo and made sure it works on iOS 14.
Thanks to @alonstar :)

**Comment by adrianpdaluz** [comment]
Thanks for your help on this. I just updated to the latest version that has the fixes for iOS14 but noticed that the picker is not centered on both tablet and phone devices. 
![Screen Shot](https://user-images.githubusercontent.com/8293376/94550127-df138080-0218-11eb-9c31-205c9ccf3879.png)

**Comment by mreall** [comment]
@shiv19 and @alonstar, thanks for providing the update.  I upgraded and am now getting the following error:
```
***** Fatal JavaScript exception - application has been terminated. *****
NativeScript encountered a fatal error: Uncaught TypeError: Cannot read property 'osVersion' of undefined
at
../node_modules/nativescript-modal-datetimepicker/modal-datetimepicker.js(file: node_modules/nativescript-modal-datetimepicker/modal-datetimepicker.ios.js:44:61)
```

The issue appears to be that you're still using `tns-core-modules` instead of `@nativescript/core`.  When the code is compiled to javascript it creates the following code. NS7 doesn't use tns-core-modules anymore.
```
Line 4: var platform_1 = require("tns-core-modules/platform");
...
Line 44: var SUPPORT_DATE_PICKER_STYLE = parseFloat(platform_1.device.osVersion) >= 14.0;
```

**Comment by shiv19** [comment]
@mreall my bad!
I only updated the demo app and changed the tns-core-modules imports there.
I didn't check the imports in the plugin source.
Just a minute.. Let me fix that quick

**Comment by shiv19** [comment]
@mreall 
Please use v2.0.0 for NativeScript 7 :)
v1.2.3 and below is for {N} 6 and below.

**Comment by mreall** [comment]
@shiv19 thanks for fixing that so quickly! It's now working for me on {N} 7 and iOS 14.  I have the same problem that @adrianpdaluz reported with the spinner not centered on the screen, but otherwise no issues.

**Comment by shiv19** [comment]
Ah! Sorry I missed the comment by @adrianpdaluz
I'll see if I can center that

**Comment by shiv19** [comment]
@mreall @adrianpdaluz 
In v2.0.1 the picker view should be centered properly :)

**Comment by adrianpdaluz** [comment]
@shiv19
Thanks again for your help on this. Could you also do another build for NS6. We have some plugin dependencies that are still not working for NS7 so we haven't finished our migration yet.

**Comment by mreall** [comment]
Thanks again @shiv19.  It's now centered properly in 2.0.1 for {N} 7 on iOS 14.

**Comment by shiv19** [comment]
@adrianpdaluz 
Use https://www.npmjs.com/package/nativescript-modal-datetimepicker/v/1.2.4 
nativescript-modal-datetimepicker@1.2.4 :)

**Comment by adrianpdaluz** [comment]
@shiv19 thank you!
