### ISSUE TITLE
Is it possible to localize the month and number values that display in the date picker?

### ISSUE THREAD

**Issue by spstratis** [davecoffin/nativescript-modal-datetimepicker#7]
I have a situation where I need the month values and day/year number values localized. Is this achievable with this plugin? 

I downloaded and have played around with the demo, but found that even when changing the OS language, the datepicker is still using english resource strings. 

I'm using tns 3.4.0 across the board right now.

**Comment by spstratis** [comment]
So it looks like on Android it will automatically translate the months but not on iOS.

**Comment by spstratis** [comment]
After playing around with it some more it looks like in order to get it to localize on iOS, you need to open up Xcode and add the localizations to the project settings.  Once you add it for each language you need, the UIDatePicker will start to display localized in the language the user has set on their phone.

**Comment by shiv19** [comment]
Thanks for the solution @spstratis

**Comment by Atomico001** [comment]
@spstratis Can you explain better how achieve this? i added the language on localization tab, but now? what i need to do?

Thanks
