### ISSUE TITLE
Old version when runing ns plugin add (crash with ns7 and ios)

### ISSUE THREAD

**Issue by Serge-SDL** [davecoffin/nativescript-modal-datetimepicker#72]
### Which platform(s) does your issue occur on?
- iOS
- emulator

### Please, tell us how to recreate the issue in as much detail as possible. 
- just run ns plugin add nativescript-modal-datetimepicker on a ns 7 project -> v1.2.4 is installed
- run on ios emulator -> error "TypeError: Cannot read property 'osVersion' of undefined"
- the 1.2.4 version is not the last one with ns7 commits !!

how can I get the ns7 updated version? (npm is not up to date)
thanks!

**Comment by romandrahan** [comment]
Same for me.

**Comment by paul-castro** [comment]
Any updates on this issue?

**Comment by davecoffin** [comment]
Sorry for the delay guys! I'll try and bang this out tomorrow, will likely move it to the https://github.com/nstudio/nativescript-plugins repo.

**Comment by davecoffin** [comment]
Ok I just published 2.1.0 for now. Should be good for supporting nativescript 7. thanks to @alonstar and @adrianpdaluz for the help!

**Comment by paul-castro** [comment]
I updated nativescript-modal-datetimepicker plugin into 2.1.0 but when I ran the project, I got this error:

-----

ERROR in ./app/features/more/bill-payment/schedule-billpay/schedule-billpay.component.ts
Module not found: Error: Can't resolve 'nativescript-modal-datetimepicker' in 
'/usr_folder/src/app/features/more/bill-payment/schedule-billpay'
 @ ./app/features/more/bill-payment/schedule-billpay/schedule-billpay.component.ts 9:0-72 82:27-46
 @ ./app/features/more/bill-payment/bill-payment.module.ts
 @ ./app/features/more/more-routing.module.ts
 @ ./app/features/more/more.module.ts
 @ ./app/app-routing.module.ts
 @ ./app/app.module.ts
 @ ./main.ts

ERROR in 6.js from Terser
Unexpected token: operator (!) [./app/features/more/bill-payment/schedule-billpay/schedule-billpay.component.ts:115,27][6.js:785,27]
    at ee (/Users/gelo/Documents/echoapp/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:19541)
    at c (/Users/gelo/Documents/echoapp/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:28244)
    at l (/Users/gelo/Documents/echoapp/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:28335)
    at f (/Users/gelo/Documents/echoapp/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:28388)
    at G (/Users/gelo/Documents/echoapp/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:42567)
    at /Users/gelo/Documents/echoapp/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:40948
    at G (/Users/gelo/Documents/echoapp/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:41074)
    at ge (/Users/gelo/Documents/echoapp/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:48272)
    at /Users/gelo/Documents/echoapp/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:49152
    at be (/Users/gelo/Documents/echoapp/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:49167)

**Comment by nikoTM** [comment]
Same, I get `Can't resolve 'nativescript-modal-datetimepicker'` with ns7

**Comment by nikoTM** [comment]
@davecoffin Something is not right about the published version, transpiled javascript is missing, only `d.ts` files are present:

<img width="267" alt="Screen Shot 2020-10-23 at 12 28 57 PM" src="https://user-images.githubusercontent.com/1929832/96987198-58a64200-152b-11eb-9928-7caeb9ac907f.png">

**Comment by razorsyntax** [comment]
Same here.  I'm getting 

`Module not found: Error: Can't resolve 'nativescript-modal-datetimepicker'`

I'm using Angular 10.1.0 and Nativescript 7.0.10

**Comment by dnepromell** [comment]
@davecoffin could you rebuild the package and publish the full version? *.ts files are miss in 2.1.0

**Comment by montxogandia** [comment]
I'm waiting for this, the @proplugins version seems to fail also in iOS 14. Thanks.
Can I solve it meanwhile or do I have to wait?

**Comment by razorsyntax** [comment]
Same as above. Is there a way to solve this without waiting for a pull request?

**Comment by montxogandia** [comment]
Guys I finally used this version that actually works on iOS 14.1 and NS 7.0.11:
https://www.npmjs.com/package/nativescript-modal-datetimepicker-ns-7

**Comment by davecoffin** [comment]
should be fixed now in 2.1.5
