### ISSUE TITLE
Uncaught ReferenceError: NativeClass is not defined NS7 on iOS14.2

### ISSUE THREAD

**Issue by mreall** [davecoffin/nativescript-modal-datetimepicker#77]
I get the following error when trying to run on a device using nativescript-modal-datetimepicker v2.1.2. The app builds successfully, then immediately crashes when loading the app.
```
***** Fatal JavaScript exception - application has been terminated. *****
NativeScript encountered a fatal error: Uncaught ReferenceError: NativeClass is not defined
at
../node_modules/nativescript-modal-datetimepicker/modal-datetimepicker.js(file: node_modules/nativescript-modal-datetimepicker/modal-datetimepicker.ios.js:27:0)
at __webpack_require__(file: app/webpack/bootstrap:74:0)
at ../node_modules/babel-loader/lib/index.js!../node_modules/vue-loader/lib/index.js?!./components/em-components/Answer.vue?vue&type=script&lang=js&(file:///app/bundle.js:1612:91)
at __webpack_require__(file: app/webpack/bootstrap:74:0)
at ./components/em-components/Answer.vue?vue&type=script&lang=js&(file: app/components/em-components/Answer.vue?1420:1:0)
at __webpack_require__(file: app/webpack/bootstrap:74:0)
at ./components/em-components/Answer.vue(file: app/components/em-components/Answer.vue:1:0)
at __webpack_require__(file: app/webpack/bootstrap:74:0)
at ../node_modules/babel-loader/lib/index.js!../node_modules/vue-loader/lib/index.js?!./components/em-components/Memory.vue?vue&type=script&lang=js&(file:///app/bundle.js:4765:65)
at __webpack_require__(file: app/webpack/bootstrap:74:0)
at ./<\M-b\M^@\M-&>
```

### Which platform(s) does your issue occur on?
- iOS 14.2 device

### Please, provide the following version numbers that your issue occurs with:
- CLI: 7.0.11
- Cross-platform modules: 7.0.13
- Runtime(s): iOS: 7.0.6
- Plugin(s): 
  "dependencies": {
    "@nativescript/appversion": "^2.0.0",
    "@nativescript/background-http": "file:../ns-plugins/plugins/dist/packages/background-http",
    "@nativescript/core": "^7.0.13",
    "@nativescript/datetimepicker": "^2.0.4",
    "@nativescript/fingerprint-auth": "^7.0.0",
    "@nativescript/firebase": "^11.1.3",
    "@nativescript/imagepicker": "^1.0.0",
    "@nativescript/iqkeyboardmanager": "^2.0.0",
    "@nativescript/secure-storage": "^3.0.0",
    "@nstudio/nativescript-exoplayer": "^5.0.4",
    "@nstudio/nativescript-pulltorefresh": "^3.0.1",
    "axios": "^0.21.0",
    "nativescript-app-tour": "^2.0.2",
    "nativescript-carousel": "^7.0.1",
    "nativescript-contacts-lite": "^0.2.7",
    "nativescript-ffmpeg-plugin-fixed": "^0.1.0",
    "nativescript-imagecropper": "^4.0.1",
    "nativescript-mediafilepicker": "^4.0.2",
    "nativescript-modal-datetimepicker": "^2.1.2",
    "nativescript-perms": "^2.0.11",
    "nativescript-toasty-ns-7": "^14.0.0",
    "nativescript-tooltip-ns": "^1.0.6",
    "nativescript-ui-listview": "^9.0.4",
    "nativescript-ui-sidedrawer": "^9.0.3",
    "nativescript-urlhandler": "^1.3.0",
    "nativescript-videorecorder-x": "^1.0.3-android-x",
    "nativescript-vue": "^2.8.3",
    "nativescript-vue-navigator": "^1.2.0",
    "vue-moment": "^4.1.0",
    "vuelidate": "^0.7.6",
    "vuex": "^3.6.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/preset-env": "^7.12.7",
    "@nativescript/android": "7.0.1",
    "@nativescript/ios": "7.0.6",
    "@nativescript/webpack": "3.0.8",
    "babel-loader": "^8.2.2",
    "dotenv-webpack": "^2.0.0",
    "nativescript-vue-template-compiler": "^2.8.3",
    "net": "^1.0.2",
    "node-sass": "^4.14.1",
    "postcss-loader": "^4.1.0",
    "vue-loader": "^15.9.5"
  },

### Please, tell us how to recreate the issue in as much detail as possible. 
The app fails immediately when I try to run it on iOS. Works fine on Android.

**Comment by paul-muckypuddle** [comment]
Also expewrienceing this issue. Looks like it occurs on another package and they've got a fix - see 

https://github.com/EddyVerbruggen/nativescript-barcodescanner/pull/248/files

**Comment by mreall** [comment]
Thanks @paul-muckypuddle and @Logikgate. FYI @davecoffin, would you mind to review the PR and publish the update when you have a minute?
